In [2]:
import pandas as pd

## Criar DataFrames utilizando os DataSets

In [3]:
# Carregar Dataframe de Clientes (Customers)
df_customers = pd.read_csv('./datasets/churn_customers.csv')

In [7]:
# Mostrar os 5 primeiros registros do DataFrame
df_customers.head(5)

   customerID  gender  SeniorCitizen Partner Dependents
0  7590-VHVEG  Female              0     Yes         No
1  5575-GNVDE    Male              0      No         No
2  3668-QPYBK    Male              0      No         No
3  7795-CFOCW    Male              0      No         No
4  9237-HQITU  Female              0      No         No

In [8]:
# Mostrar os 5 últimos registros
df_customers.tail(5)

      customerID  gender  SeniorCitizen Partner Dependents
7038  6840-RESVB    Male              0     Yes        Yes
7039  2234-XADUH  Female              0     Yes        Yes
7040  4801-JZAZL  Female              0     Yes        Yes
7041  8361-LTMKD    Male              1     Yes         No
7042  3186-AJIEK    Male              0      No         No

In [9]:
# Mostrar estrutura / schema do DataFrame
df_customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     7043 non-null   str
 1   gender         7043 non-null   str
 2   SeniorCitizen  7043 non-null   int64
 3   Partner        7043 non-null   str
 4   Dependents     7043 non-null   str
dtypes: int64(1), str(4)
memory usage: 275.2 KB

In [10]:
# Carregar Dataframe de Serviços (Services)
df_services = pd.read_csv('./datasets/churn_services.csv')

In [11]:
df_services.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   PhoneService      7043 non-null   str
 2   MultipleLines     7043 non-null   str
 3   InternetService   7043 non-null   str
 4   OnlineSecurity    7043 non-null   str
 5   OnlineBackup      7043 non-null   str
 6   DeviceProtection  7043 non-null   str
 7   TechSupport       7043 non-null   str
 8   StreamingTV       7043 non-null   str
 9   StreamingMovies   7043 non-null   str
dtypes: str(10)
memory usage: 550.4 KB

In [12]:
# Mostrar os 5 primeiros registros do DataFrame
df_services.head(5)

,customerID,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,No,No phone service,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,Yes,No,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,Yes,No,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,No,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,Yes,No,Fiber optic,No,No,No,No,No,No

In [13]:
# Mostrar os 5 últimos registros
df_customers.tail(5)

      customerID  gender  SeniorCitizen Partner Dependents
7038  6840-RESVB    Male              0     Yes        Yes
7039  2234-XADUH  Female              0     Yes        Yes
7040  4801-JZAZL  Female              0     Yes        Yes
7041  8361-LTMKD    Male              1     Yes         No
7042  3186-AJIEK    Male              0      No         No

In [14]:
# Carregar Dataframe de Contratos (Contracts)
df_contracts = pd.read_csv('./datasets/churn_contracts.csv')

In [15]:
df_contracts.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   tenure            7043 non-null   int64
 2   Contract          7043 non-null   str
 3   PaperlessBilling  7043 non-null   str
 4   PaymentMethod     7043 non-null   str
 5   MonthlyCharges    7043 non-null   float64
 6   TotalCharges      7043 non-null   str
 7   Churn             7043 non-null   str
dtypes: float64(1), int64(1), str(6)
memory usage: 440.3 KB

In [16]:
# Mostrar os 5 primeiros registros do DataFrame
df_contracts.head(5)

,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,2,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [17]:
# Mostrar os 5 últimos registros
df_contracts.tail(5)

,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,24,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,72,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,11,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,4,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,66,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

## Transformação de Dados

In [ ]:
# Transformar coluna TotalCharges de String para Float - Abordagem 1 com astype
# df_contracts.TotalCharges (não funciona com nomes que tenham espaco) ou df_contracts['TotalCharges']
df_contracts['TotalCharges'] = df_contracts.TotalCharges.astype(float)
# Nesse caso vai dar erro pois tem espaço em branco nos registros (não consegue transformar espaço em branco em float)

In [ ]:
# Transformar coluna TotalCharges de String para Float - Abordagem 2 com to_numeric
df_contracts['TotalCharges'] = pd.to_numeric(df_contracts.TotalCharges)
# Nesse caso vai dar erro pois tem espaço em branco nos registros (não consegue transformar espaço em branco em float)

In [ ]:
# Transformar coluna TotalCharges de String para Float - Abordagem 3 com to_numerico com coerce
df_contracts['TotalCharges'] = pd.to_numeric(df_contracts.TotalCharges, errors='coerce')
# Nesse caso a transformação vai acontecer, pois onde tem espaço em branco ou algo que ele não consiga converter, vai se transformar em nulo/null

In [19]:
# Mostrar estrutura / Schema do DataFrame para verificar transformação
df_contracts.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   tenure            7043 non-null   int64
 2   Contract          7043 non-null   str
 3   PaperlessBilling  7043 non-null   str
 4   PaymentMethod     7043 non-null   str
 5   MonthlyCharges    7043 non-null   float64
 6   TotalCharges      7032 non-null   float64
 7   Churn             7043 non-null   str
dtypes: float64(2), int64(1), str(5)
memory usage: 440.3 KB

Após a transformação da coluna TotalCharges do DataFrame Contracts, a coluna passou a ter 11 valores ausentes (missing values)

## Renomear colunas

In [20]:
df_customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     7043 non-null   str
 1   gender         7043 non-null   str
 2   SeniorCitizen  7043 non-null   int64
 3   Partner        7043 non-null   str
 4   Dependents     7043 non-null   str
dtypes: int64(1), str(4)
memory usage: 275.2 KB

In [ ]:
# Renomear coluna no DataFrame, usando rename e dicionário
df_customers.rename(columns={'SeniorCitizen': 'Above65yo'})
# Mostra o resultado da renomeação, mas nao altera o DataFrame como mostrado a seguir

      customerID  gender  Above65yo Partner Dependents
0     7590-VHVEG  Female          0     Yes         No
1     5575-GNVDE    Male          0      No         No
2     3668-QPYBK    Male          0      No         No
3     7795-CFOCW    Male          0      No         No
4     9237-HQITU  Female          0      No         No
...          ...     ...        ...     ...        ...
7038  6840-RESVB    Male          0     Yes        Yes
7039  2234-XADUH  Female          0     Yes        Yes
7040  4801-JZAZL  Female          0     Yes        Yes
7041  8361-LTMKD    Male          1     Yes         No
7042  3186-AJIEK    Male          0      No         No

[7043 rows x 5 columns]

In [22]:
df_customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     7043 non-null   str
 1   gender         7043 non-null   str
 2   SeniorCitizen  7043 non-null   int64
 3   Partner        7043 non-null   str
 4   Dependents     7043 non-null   str
dtypes: int64(1), str(4)
memory usage: 275.2 KB

In [23]:
# Criar um DataFrame novo com base nas colunas renomeadas
df_customers_renamed = df_customers.rename(columns={'SeniorCitizen': 'Above65yo'})

In [24]:
# Mostar nova estrutura do DataFrame após a renomeação
df_customers_renamed.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerID  7043 non-null   str
 1   gender      7043 non-null   str
 2   Above65yo   7043 non-null   int64
 3   Partner     7043 non-null   str
 4   Dependents  7043 non-null   str
dtypes: int64(1), str(4)
memory usage: 275.2 KB

In [29]:
# Aplicar o rename no próprio DataFrame
df_customers.rename(columns={'SeniorCitizen': 'Above65yo'}, inplace=True)

In [33]:
# Visualizar nova estrutura após renomeação
df_customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerID  7043 non-null   str
 1   gender      7043 non-null   str
 2   Above65yo   7043 non-null   int64
 3   Partner     7043 non-null   str
 4   Dependents  7043 non-null   str
dtypes: int64(1), str(4)
memory usage: 275.2 KB

In [ ]:
# Rename usando Lista - Modificar todos os nomes de colunas
df_customers.columns = ['IDCliente', 'Genero', 'above65yo', 'TemParceiro', 'TemDependentes']
# Troca todos os nomes das colunas (Precisa seguir a ordem)

## Unificar DataFrames de customers, services e contracts

In [34]:
# Contar quantidade de registros por DataFrame
len(df_customers)

7043

In [35]:
len(df_contracts)

7043

In [36]:
len(df_services)

7043

In [37]:
# Unificar DataFrame de customers com services, criando um terceiro DataFrame
df_temp = df_customers.merge(df_services, on=['customerID'])

In [38]:
# Mostar o DataFrame criado
df_temp.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   Above65yo         7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   PhoneService      7043 non-null   str
 6   MultipleLines     7043 non-null   str
 7   InternetService   7043 non-null   str
 8   OnlineSecurity    7043 non-null   str
 9   OnlineBackup      7043 non-null   str
 10  DeviceProtection  7043 non-null   str
 11  TechSupport       7043 non-null   str
 12  StreamingTV       7043 non-null   str
 13  StreamingMovies   7043 non-null   str
dtypes: int64(1), str(13)
memory usage: 770.5 KB

In [39]:
df_temp.head(5)

,customerID,gender,Above65yo,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,Female,0,Yes,No,No,No phone service,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,Male,0,No,No,Yes,No,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,Male,0,No,No,Yes,No,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,Male,0,No,No,No,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,Female,0,No,No,Yes,No,Fiber optic,No,No,No,No,No,No

In [ ]:
# EXEMPLO
# Unificar df_temp com contracts, usando colunas de junção com nomes distintos
# df_churn_temp = df_temp.merge(df_contracts, left_on=['ClienteID'], right_on=['customerID'])
# Fazendo dess maneira, a coluna ficaria duplicada dentro do DataFrame (teria que dar um drop em uma coluna para não ficar duplicada)

In [40]:
df_churn_temp = df_temp.merge(df_contracts, on=['customerID'])

In [41]:
df_churn_temp.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   Above65yo         7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   PhoneService      7043 non-null   str
 6   MultipleLines     7043 non-null   str
 7   InternetService   7043 non-null   str
 8   OnlineSecurity    7043 non-null   str
 9   OnlineBackup      7043 non-null   str
 10  DeviceProtection  7043 non-null   str
 11  TechSupport       7043 non-null   str
 12  StreamingTV       7043 non-null   str
 13  StreamingMovies   7043 non-null   str
 14  tenure            7043 non-null   int64
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.1 MB

In [42]:
df_churn_temp.head(5)

,customerID,gender,Above65yo,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,TechSupport,StreamingTV,StreamingMovies,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,No,No phone service,DSL,No,Yes,...,No,No,No,1,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,Yes,No,DSL,Yes,No,...,No,No,No,34,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,Yes,No,DSL,Yes,Yes,...,No,No,No,2,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,No,No phone service,DSL,Yes,No,...,Yes,No,No,45,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,Yes,No,Fiber optic,No,No,...,No,No,No,2,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [43]:
# unificar os 3 DataFrames ao mesmo tempo
df_churn = df_customers.merge(df_services, on=['customerID']).merge(df_contracts, on=['customerID'])

In [44]:
df_churn.head(5)

,customerID,gender,Above65yo,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,TechSupport,StreamingTV,StreamingMovies,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,No,No phone service,DSL,No,Yes,...,No,No,No,1,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,Yes,No,DSL,Yes,No,...,No,No,No,34,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,Yes,No,DSL,Yes,Yes,...,No,No,No,2,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,No,No phone service,DSL,Yes,No,...,Yes,No,No,45,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,Yes,No,Fiber optic,No,No,...,No,No,No,2,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [45]:
df_churn.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   Above65yo         7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   PhoneService      7043 non-null   str
 6   MultipleLines     7043 non-null   str
 7   InternetService   7043 non-null   str
 8   OnlineSecurity    7043 non-null   str
 9   OnlineBackup      7043 non-null   str
 10  DeviceProtection  7043 non-null   str
 11  TechSupport       7043 non-null   str
 12  StreamingTV       7043 non-null   str
 13  StreamingMovies   7043 non-null   str
 14  tenure            7043 non-null   int64
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.1 MB

In [ ]:
# EXEMPLO
# unificar os 3 DataFrames ao mesmo tempo, com colunas com nomes diferentes
# df_churn = df_customers.merge(df_services, on=['IDCLiente']).merge(df_contracts, left_on=['IDCliente'], right_on=['customerID'])
# também ficaria com o problema dos dados duplicados

In [ ]:
# Removendo coluna do DataFrame
# df_churn.drop(['ClienteID'], axis=1, inplace=True)
# axis é linha (0) ou coluna (1)